### ISSUE TITLE
Support `Shelly EM`

### ISSUE THREAD

**Issue by milkpirate** [tasmota/mgos32-to-tasmota32#13]
Hey,

I bought the Shelly above lately and would like to flash Tasmota. Could you support it was well? Or tell me which device is compatible?

Details: https://www.shelly.com/en-de/products/product-overview/shelly-em-120a

Best regards

**Comment by Jason2866** [comment]
There is no convert package compatible. Every package needs to be built with the exact internal Shelly name for the device.
