### ISSUE TITLE
Re-add support for Shelly Plus Plug UK (type G)

### ISSUE THREAD

**Issue by rweir** [tasmota/mgos32-to-tasmota32#15]
Hi,

earlier this year, I used the [instructions](https://github.com/tasmota/mgos32-to-tasmota32/blob/0940da80ff10da3fd2e1f53534082f7f2886bb3c/README.md#supported-devices-and-ota-links) from this repository to flash Tasmota to a Shelly Plus Plug UK.  I've now come back to flash some new ones, but I've found the instructions have been updated to use Github-hosted archives and there is no longer one for the UK version of the Plus Plug.  I've tried the [PlusPlugS.zip](https://github.com/tasmota/mgos32-to-tasmota32/releases/download/v13.1/mgos32-to-tasmota32-PlusPlugS.zip) which seemed like it might work but Shelly logs this error:

> Wrong app name 'PlusPlugS'

and then aborts flashing.

Is it possible to re-add support for that model or even just re-post a copy of the old file which used to be at http://ota.tasmota.com/tasmota32/shelly/mgos32-to-tasmota32-PlusPlugUK.zip ?

Thanks!

**Comment by Jason2866** [comment]
Thx, for the PR. Is there a PlugUK based on an ESP32? If not i can remove.

**Comment by Jason2866** [comment]
It is wrong. Fixed the other PlusPlug(s) packages too.
