### ISSUE TITLE
Shelly Plus Wall Dimmer

### ISSUE THREAD

**Issue by kunaalm** [tasmota/mgos32-to-tasmota32#17]
I am attempting to migrate a Shelly Plus Wall Dimmer to Tasmota (I know it's untested!). I don't see any GPIO mapping after autoconfig. Is the template known / defined somewhere?

**Comment by Jason2866** [comment]
You are the first. So no.

**Comment by tkffaul** [comment]
I have one as well that I would like to convert. I have the boot loader up and running but still no GPIO mapping?

**Comment by Jason2866** [comment]
Since no feedback from users which have the device how the GPIOs are assigned, I can't add them.

**Comment by tkffaul** [comment]
I know this is probably more involved, but I'm not a complete noob... can you guide me on how to check GPIO and maybe I can help provide a map? I have a temporary rig setup for this already, i have a serial over USB connector I can hook on to it... I just don't know how to proceed to map the pin sets.

**Comment by Jason2866** [comment]
Without open the device this can be a useless attempt. If dimming is done via a second MCU the train stops here.
In this case a complete reverse engineering is needed or a dimming firmware needs to be done. Like it was done for the Shelly Dimmer.
If all work is done by the ESP32 the journey goes on :-)

**Comment by tkffaul** [comment]
So if i crack the case and take some photos, that would be helpful? I know shelly has stated that this is very different than the original dimmers... so (just an assumption) i think it might do everything from the ESP32 now.

**Comment by Jason2866** [comment]
Yes, photos will help. So no guessing about "who" does the dimming. Maybe it can be seen which GPIOs goes to the FETs

**Comment by tkffaul** [comment]
![IMG_4017](https://github.com/tasmota/mgos32-to-tasmota32/assets/55748571/a5e15e1d-8351-4464-ae32-5f6f17587565)
Back of Switch

**Comment by tkffaul** [comment]
![IMG_4018](https://github.com/tasmota/mgos32-to-tasmota32/assets/55748571/130a6ccc-d8bb-4fc1-9cbe-a09c0b274079)
Inside

**Comment by tkffaul** [comment]
![IMG_4024](https://github.com/tasmota/mgos32-to-tasmota32/assets/55748571/2a9e663d-b54c-4b3f-8cfa-1d2bea52e5e3)
Zoom in of the ESP32

**Comment by tkffaul** [comment]
![IMG_4023](https://github.com/tasmota/mgos32-to-tasmota32/assets/55748571/3d5bddee-518d-479b-b3ea-e2b31fc42754)

**Comment by tkffaul** [comment]
![IMG_4025](https://github.com/tasmota/mgos32-to-tasmota32/assets/55748571/8f039475-b969-4265-bb0c-9ca23028647e)
![IMG_4026](https://github.com/tasmota/mgos32-to-tasmota32/assets/55748571/3e53ff66-b699-4cfa-a1f8-19a7f9297c6a)
![IMG_4027](https://github.com/tasmota/mgos32-to-tasmota32/assets/55748571/b9041f77-30b0-425e-93f3-e99134bab0c7)

**Comment by tkffaul** [comment]
Hope that helps!

**Comment by Jason2866** [comment]
Yes, it does help. I think this IC is an MCU
<img width="221" alt="Bildschirmfoto 2024-04-25 um 11 04 07" src="https://github.com/tasmota/mgos32-to-tasmota32/assets/24528715/32eb7fdb-925f-4491-a3dc-2076dc5b8108">
since it is placed on the AC power PCB it probably does the dimming job and the ESP32 "just tells" to do so.
Did not find any data sheet for this IC

Looks like flashing Tasmota does lead to nowhere. Thx for the photos!!

**Comment by RavenSystem** [comment]
It is an STM32S003. Best way is to use a logic analyzer to read UART communication between ESP32 and it, with the original Shelly firmware loaded, of course.

**Comment by Jason2866** [comment]
Closing support not planned.
