### ISSUE TITLE
tasmota32-to-mgos32 over serial?

### ISSUE THREAD

**Issue by sVnsation** [tasmota/mgos32-to-tasmota32#19]
Hello! 
I converted my Shelly Pro 4PM to tasmota. 
Also noticed the warning "There is no way back to Shelly firmware if you have initiated the convert process!" and thought: i don't want to revert anyway.

But currently im a bit unhappy with the solution for the Pro 4PM:
- More energy consumption in standby: 1.6W with tasmota32 instead of 0.9W on stock
- Display and Buttons not working correctly

Is there a way back to stock? Maybe over serial flash?

**Comment by Jason2866** [comment]
No, the warning is there for a reason. If you would have dumped the whole flash via serial it is possible to write it back. The OTA convert process can't save the calibration data and the security certificates.
