### ISSUE TITLE
Shelly Plug Plus S cannot be reset?

### ISSUE THREAD

**Issue by ojkastl** [tasmota/mgos32-to-tasmota32#21]
I successfully flashed Tasmota on my Shelly Plug Plus S, but after setting a static IP (or was it the safeboot modification, not sure) it does no work.

It seems to connect to my Wifi (I can see the device in my router), but I cannot reach it in any way I tried.

It does not offer a Wifi (neither Tasmota nor the Shelly one), it does not respond to pings, I cannot open the IP via browser, nmap shows it as "not up").

I tried resetting according to the docs, but up to no it does not respond to anything:
- fast power cycle (turn on/off six times)
- hold reset button for 40s

Is there anything I can try to get this working again?

Thanks in advance!

**Comment by Jason2866** [comment]
> It seems to connect to my Wifi (I can see the device in my router), but I cannot reach it in any way I tried.

If it is connected it will not have an AP. Tried to restart the router? Sometimes the have hick ups. If this does not help there is nothing left you can try. You did already everything.

Try to open and serial flash is the only way out.

**Comment by ojkastl** [comment]
Hmmmm. I am not sure what I did, but it works now.

The router was restarted multiple times, but the device still did not work.

Now I took it to a different part of the house, and for some reason it suddenly connected. With the static IP I had configured. WTF?

Anyway, thanks for your quick response!
