### ISSUE TITLE
Update-process for Shelly Pro 2PM unclear

### ISSUE THREAD

**Issue by ChristianWaechter** [tasmota/mgos32-to-tasmota32#39]
Hello,

I'm trying to flash my Shelly Pro 2PM with Tasmota. After searching for it, I found this page: https://templates.blakadder.com/shelly_pro_2pm.html

This lead me to this [mgos32-to-tasmota32](https://github.com/tasmota/mgos32-to-tasmota32) repository. In the step by step help it is first recommended to update to the latest firmware. I assume that a update to the latest Shelly fimware is meant.
> Prerequisites
> 1. ⚠️ Needed ⚠️ Update the device to the latest stable firmware (Internet access!!)

In my case, Shelly firmware 0.14.1 is currently installed and 1.1.0 (Stable) would be available. But I somehow do not want to update, as the [Tasmota page](https://templates.blakadder.com/shelly_pro_2pm.html) notes
>  WARNING!!! Devices with firmaware v1.10+ cannot be flashed OTA anymore

So what is the correct procedure? I do not want to lock the Shelly just because I updated to version 1.1.0.

Thanks in advance :)

**Comment by Jason2866** [comment]
The text you copied is outdated. See actual README

**Comment by ChristianWaechter** [comment]
> The text you copied is outdated.
You mean the text on the Tasmota website?

> See actual README
I found in an older commit from 21.23.2023 of this repository that a fix for the Shelly firmware 1.1.0 has been included. So that means that I safely can update my Shelly firmware and than switch to Tasmota :)

**Comment by ChristianWaechter** [comment]
I was a bit overhasty and answered before actually trying it. Long story short, I cannot flash the Tasmota firmware.

What I did step by step:
1) Powered up the Shelly, only the power is connected to the L and N connector
2) Connected to its Wifi access point and configured it so it can establish a connection to my actual Wifi (Router is directly next to the Shelly). Reconnected with my actual Wifi and again accessed the web interface of the Shelly
3) I did the update of the Shelly firmware from 0.14.1 to 1.1.0 (Stable) via the web interface. After it was done, the Shelly rebooted and I saw clear differences in the web interface. Also the firmware reports with Firmware ID _20231219-133937/1.1.0-g34b5d4f_ and Webbuild ID _231218152112-8372d8c8-HEAD_
4) I downloaded the file "mgos32-to-tasmota32-Pro2PM.zip" from Release v13.3.1 and dragged it into the "Firmware file image"-field in the Shelly webinterface. I also tried to  browse and choose the file that way. It shows in the web interface: _mgos32-to-tasmota32-Pro2PM.zip: 2127374 bytes_
5) I Press the "Update from file"-button. In the very top of the webinterface _System update in progress... [View settings]_ appears. After ~ 5 seconds it disappiers again by its own. Nothing other is shown. The page stays like this for ever.
6) Clicking the "Update from file"-button again shows the exact same behaviour as in 5)
7) I after that I did a complete power cycle of the shelly and tried steps 4 - 6 again with no change.

Am I missing something?

**Comment by ChristianWaechter** [comment]
![grafik](https://github.com/tasmota/mgos32-to-tasmota32/assets/46220276/95a2515b-9fec-4eaf-abfc-09e626e36086)

**Comment by Jason2866** [comment]
Thx. Looks like, Shelly changed "something", which is different to the changes done to the mini g3 devices. The Tasmota convert firmware is working with Shelly 1.1.0 gen3 devices.
The good news, nothing has been altered on your Shelly device.

**Comment by ChristianWaechter** [comment]
So it is not possible to flash Tasmota onto this device? Where can you see whether or not it's a Shelly 1.1.0 gen3 device?

**Comment by Jason2866** [comment]
It is not a gen3 device. In the upper left side there is the exact device name.
Converting will be probably possible, i have to look where it fails. Will need some time because i have not much spare time currently.

**Comment by Jason2866** [comment]
Bug identified. Working on the fix.

**Comment by Jason2866** [comment]
Closing since no feedback
