### ISSUE TITLE
Cannot flash on Shelly 1PM Pro

### ISSUE THREAD

**Issue by vpant** [tasmota/mgos32-to-tasmota32#41]
I bought multiple shelly devices (mostly 1PMs and 2PMs) and I flashed everything with tasmota. The only one I cannot flash is the 1PM Pro that I bought to control my water heater.

The ota flash starts but then it is almost immidiately stops without any error except one in the console:
![Screenshot from 2024-01-19 10-44-07](https://github.com/tasmota/mgos32-to-tasmota32/assets/11424758/11a63371-ab65-4f3f-9a1b-f06ecd61798d)

I also enabled the debug logs:
[diagnostics-shelly-pro1pm-debug-log.txt](https://github.com/tasmota/mgos32-to-tasmota32/files/13986641/diagnostics-shelly-pro1pm-debug-log.txt)

**Comment by Jason2866** [comment]
Thx, for the log. Shelly changed (again) something.
This
```Aborting update: backend error while processing data: -1 (-10: New app_1 overlaps with current app_0)"```
shows that probably the partition scheme does not fit to the latest firmware.

**Comment by macSE1990** [comment]
I have the same problem on Shelly Pro 1 v.1 (without PM)

**Comment by Jason2866** [comment]
Bug identified. Working on the fix.

**Comment by Jason2866** [comment]
Should be fixed with latest release 13.4.1

**Comment by Jason2866** [comment]
Closing since no feedback

**Comment by macSE1990** [comment]
Confirming success for Shelly Pro 1 v.1
Sorry for the late answer.
