### ISSUE TITLE
Shelly Plus1Mini - No Partition Manager

### ISSUE THREAD

**Issue by petereit** [tasmota/mgos32-to-tasmota32#42]
Trying to flash a Shelly Plus1 Mini.

I upgrade Shelly firmware to v1.10, dragged the mgos32-to-tasmota32-Plus1Mini.zip file and click update.

Got to step 10. I click Console, but there is no Partition Wizard option. These are my only options:

Console
Berry Scripting console
Manage File system
Main Menu

**Comment by Jason2866** [comment]
So step 8 failed. Does the device has Internet access?

**Comment by petereit** [comment]
Yes. The device has internet access. 

I was able to copy the Partition Wizard .tapp, reboot and start the Safeboot Conversion, but now it’s stuck in Safeboot.

**Comment by Jason2866** [comment]
When step 8 is not completely successful (replacing bootloader) it stuck.
Only serial flash is the way to solve.

**Comment by Jason2866** [comment]
Can not reproduce the issue. Tried a few times, always successful.
