### ISSUE TITLE
Shelly Plus Uni

### ISSUE THREAD

**Issue by elngejw** [tasmota/mgos32-to-tasmota32#43]
Hi good day!

Do you also have a convert file I can use for Shelly Plus Uni?
https://www.shelly.com/en-nl/products/product-overview/shelly-plus-uni-1

Many thanks and best regards,

Geert-Jan

**Comment by Jason2866** [comment]
There is a chance to get it done. Can you post a screenshot of the firmware update page?
In upper left corner there should be the intern Shelly device name shown.
Knowing the name, there should be possible to download a update package. All needed Infos to build a convert package should be there.

**Comment by elngejw** [comment]
First of all thx for your quick reply!
Find attached the requested screenshot.

![Schermafbeelding 2024-01-24 213331](https://github.com/tasmota/mgos32-to-tasmota32/assets/111745797/88f950a5-490f-4dfe-b00e-c42a624a7bb1)

**Comment by MinGeunJang** [comment]
I look forward to the tasmota firmware for Shelly Plus Uni.

**Comment by Jason2866** [comment]
Added Shelly Plus Uni
The Autoconfig does not set any GPIOs since I don't have the device.
You have to find out the configuration yourself. Would be great if you post your findings.

**Comment by MenesesPT** [comment]
I followed the instructions in the readme and was able to convert a Shelly Plus Uni to Tasmota successfully.

I then managed to find the following pinout:
| **Shelly** | **GPIO** | **Tasmota** |
|------|------|------|
| Data  |   13   | AM2301 (or DS18x20)
| Led    |   18   | Led_i 1
| Out 1 |   19   | Relay 1
| Out 2 |   21   | Relay 2
| N/A   |   25   | ADC Range 1
| Analog In   |   36   | ADC Input 1
| In 2  |   37   | Switch_n 2
| In 1  |   38   | Switch_n 1
| Count In  |   36   | Switch_n 3

Which gives the following template: 
`{"NAME":"Shelly Plus Uni","GPIO":[0,0,0,0,0,0,0,0,0,1216,0,0,0,0,320,224,0,225,0,0,0,4864,0,0,0,0,0,0,0,0,0,0,4704,193,192,194],"FLAG":0,"BASE":1}`

> [!NOTE]  
> 1. I did not test any sensors on **GPIO13** since I don't own any;
> 2. Changing **GPIO25** output value seems to change the values read on **GPIO36**, I used *ADC Range* but I'm not sure if that is correct;
> 3. The **Count In** pin was defined as a normal switch input.

Given that my shelly has an ESP32-U4WDH-D with two cores, I then replaced the solo version of Tasmota with the dual-core one without any issues.

Thanks for the conversion firmware!

**Comment by Jason2866** [comment]
Thx, added to Autoconfig.
