### ISSUE TITLE
Migrate to safeboot partition layout problem

### ISSUE THREAD

**Issue by bilbolodz** [tasmota/mgos32-to-tasmota32#45]
I've converted my Shelly I4 DC to Tasmota using mgos32-to-tasmota32 and it's working fine but I've tasmote version 12.5
I've tried to OTA update to newest (13.3.0) but upgrade fails due to: "Program flash size is larger than real flash size".
I've tried with Partition Wizard to "Migrate to safeboot partition layout" but after running it I've ended with ..... back to original Shelly firmware. Any ideas how to get newest Tasmota on Shelly I4 and possibility to upgrade it with OTA?

**Comment by Jason2866** [comment]
Step 8 was not done immediately or was not successful. Serial flash is needed.

**Comment by bilbolodz** [comment]
Indeed step 8 was not done but which device profile should I use? There is no Shelly I4 profile:
![obraz](https://github.com/tasmota/mgos32-to-tasmota32/assets/4696144/3dc2f0bc-f908-4f47-bf6b-8c52a5a050f8)

**Comment by bilbolodz** [comment]
Yep, my fault. Now all is working fine!
