### ISSUE TITLE
Shelly Pro 2 - Firmware 1.2.2 - not possible to flash

### ISSUE THREAD

**Issue by RaidObServer** [tasmota/mgos32-to-tasmota32#48]
My new Shelly Pro 2 has been updated to version 1.2.2. 
With this version it is not possible to download the current mgos32-to-tasmota32-Pro2.zip file.

![shelly_pro_2](https://github.com/tasmota/mgos32-to-tasmota32/assets/112802138/f09e90da-b8ca-40c6-8a18-0d97cd3ff60a)

![shelly_pro_2_log](https://github.com/tasmota/mgos32-to-tasmota32/assets/112802138/f7014ad0-ef5e-49a4-8663-ecd886e3c0c8)

Could you please check if an update is possible?

best regards & many thanks
Stefan

**Comment by Jason2866** [comment]
To rule out misunderstandings. The convert package was provided via file upload or via drop down in the marked area?
It is **not** possible to provide the convert package via Link!!

**Comment by RaidObServer** [comment]
correct, the file was dragged and dropped into the marked area.

It is also interesting to note that the mgos32-to-tasmota32-Pro2 version 13.1 update runs up to 73%. However, it does not start with the current version 13.3.1. I have added both diagnostics files.

[diagnostics-shelly-pro2-debug-log_v13_1.txt](https://github.com/tasmota/mgos32-to-tasmota32/files/14439988/diagnostics-shelly-pro2-debug-log_v13_1.txt)
[diagnostics-shelly-pro2-debug-log_v13_3_1.txt](https://github.com/tasmota/mgos32-to-tasmota32/files/14439990/diagnostics-shelly-pro2-debug-log_v13_3_1.txt)

**Comment by RavenSystem** [comment]
@Jason2866 Error is the same type of other times:

`app / fs already written, can't update boot`

Meaning that `boot` part must be added to zip file before than `app` and `fs`.

**Comment by RavenSystem** [comment]
@Jason2866 FYI. I downloaded last Plus 1PM official firmware 1.2.2, and the official order of the files is:
- bootloader.bin
- partition-table.bin
- otadata.bin
- Plus1PM.bin
- fs.img

**Comment by RavenSystem** [comment]
@Jason2866 I think current issue is the size of Tasmota binary.

**Comment by Jason2866** [comment]
@RavenSystem  The currently used partition table is incompatible.
Guess the partition table has changed again for Shelly fw 1.2.x.
Can currently not investigate, no time for.

**Comment by jeroenst** [comment]
I also upgraded a Shelly 2PM Plus to 1.2.2 and I can't find any way to downgrade it so I can flash Tasmota to it. Hopefully it will be possible in the future. I think I return the unit and get a new one with stock firmware.

**Comment by Jason2866** [comment]
Try again, Issue should be fixed.

**Comment by dr-m** [comment]
For what it is worth, I successfully upgraded a freshly purchased Shelly 2 Pro to firmware 1.3.0 and then to Tasmota using the appropriate package. Thank you!
