### ISSUE TITLE
Step 8. - no Plus10V in the auto-configuration List

### ISSUE THREAD

**Issue by Peeri90** [tasmota/mgos32-to-tasmota32#51]
Hello,
i have a Problem with the step 8. i cant find the Shelly Plus10V under  Configuration > Auto-configuration > Select new auto-configuration. 

i use the mgos32-to-tasmota32-Plus10V.zip from Dec 31, 2023

![no10V](https://github.com/tasmota/mgos32-to-tasmota32/assets/34984619/fe42275f-b723-4c9c-ab9f-a274b860b1f1)

what can i do ? Thanks for your time

**Comment by berndh1979** [comment]
Same issue here. I guess that is why the device after flashing is not working anymore.

**Comment by Jason2866** [comment]
Yes, there is no Autoconfig for the Plus10V. Simple reason idk what to configure.

**Comment by Jason2866** [comment]
Added the device to the Autoconfig to prevent bricking during convert process.
There are NO GPIOs configured since I don't have the device.
You have to find out this yourself. It would be great if you post your found config.

**Comment by Jason2866** [comment]
Update Autoconfig with GPIO settings
