### ISSUE TITLE
2PM schaltet selbstständig aus

### ISSUE THREAD

**Issue by Marc9485** [tasmota/mgos32-to-tasmota32#53]
Hey, ich hab meinen Shelly 2PM mit Tasmota geflasht aber habe das Problem, das dieser beide Kanäle selbst ausschaltet. Home Assistant schließe ich als Fehler aus da dort kekn Dienst erscheint der ausschaltet. Kann mir da jemand helfen?
![image](https://github.com/tasmota/mgos32-to-tasmota32/assets/134625027/7c247684-0152-40c6-8f20-6b4e044566ef)

**Comment by Jason2866** [comment]
Not the correct place for discussions which are not related to the convert process.

**Comment by Marc9485** [comment]
OK, my thought was that there was a problem with the flash because Home Assistant, as you can see in the picture, doesn't give a command to switch it off but only recognizes that it has been switched off, so the Shelly must have a life of its own. And there is no field for “discussions” here otherwise I would ask it there.
