### ISSUE TITLE
Shelly Pro Dimmer 2PM

### ISSUE THREAD

**Issue by justspacedog** [tasmota/mgos32-to-tasmota32#59]
Hi,

please add a build for this device:
https://kb.shelly.cloud/knowledge-base/shelly-pro-dimmer-2pm

Thank you!

**Comment by Jason2866** [comment]
Need the device name visible on the Shelly device Web page.
Please post a screenshot from.

**Comment by Jason2866** [comment]
There is no update package available for this device from Shelly update server.
https://updates.shelly.cloud/update/ProDimmer2PM
To make a convert package I need infos from this package. As long there is no update is available no dice.

**Comment by Jason2866** [comment]
There are flash pin headers. If you can dump the installed firmware (8MB), and provide me the dump I could try do too.

**Comment by justspacedog** [comment]
That would be awesome! How can I do the dump?

**Comment by Jason2866** [comment]
See https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/basic-commands.html#read-flash-contents-read-flash
You need hardware for. Recommended https://tasmota.github.io/docs/Getting-Started/

**Comment by justspacedog** [comment]
I have a serial interface somewhere, but we just moved and I don’t know where I put it… :/

I activated debugging on the WebInterface and found out, that the update URL uses the Identifier „ProDimmerx“:
https://updates.shelly.cloud/update/ProDimmerx

![Image 24 04 24 at 19 57](https://github.com/tasmota/mgos32-to-tasmota32/assets/8201551/740fabca-8149-4b49-aa16-1af3d8a166d8)

So the stable Firmware should be found under:
https://fwcdn.shelly.cloud/gen2/ProDimmerx/d6d452c462e2e60e7106ff8996c0ac6184c0ba984d96a5490f5adf9874b6ea4e

It’s a 2,2 MB Zip Archive. Can you work with that or do you need the dump?

**Comment by Jason2866** [comment]
If it is similar to #17 it is not supported from Tasmota

**Comment by Jason2866** [comment]
Closing support not planned.
