### ISSUE TITLE
shelly plus 1pm

### ISSUE THREAD

**Issue by avacon34** [tasmota/mgos32-to-tasmota32#6]
there is no convert *.zip file in release section. I downloaded the archive for shelly plus 1pm and did what you said at least 10 times and all the time shelly did not flashed.

I am writing this after flashing 12 pcs plus2pm, 11 pcs plus 1pm and 3 pcs plusi4 within a month. After shelly 1.0.3 firmware it is not flashing anymore.

**Comment by Maximillian** [comment]
I am also trying to flash a Shelly (Plus1) running 1.0.3 and it just fails. 1.0.3 was released on Sept 12, so it must have broken this firmware.

**Comment by Colorado4Wheeler** [comment]
Perhaps it is the 1.0.3 but I don't even see where you can drag the firmware into the Shelly Plus 1PM.  This is my first time trying this but I only see this in firmware, let alone get to the failure you are discussing.

![image](https://github.com/tasmota/mgos32-to-tasmota32/assets/20329385/ead327da-49df-4148-adf4-2d9ee39df916)

**Comment by avacon34** [comment]
Do a factory reset and add device once again. Hopefully it will appear.

24 Eyl 2023 Paz 01:19 tarihinde Colorado Four Wheeler <
***@***.***> şunu yazdı:

**Comment by Colorado4Wheeler** [comment]
@avacon34 yes, it was something like that, apparently I was in the AP mode setup that doesn't have it, once I went to the actual post-setup IP it had that.  I had deleted my message after I discovered that, sorry you replied unnecessarily.

**Comment by Jason2866** [comment]
The "*" is a placeholder for the corresponding package of your device.
Our test are made with Shelly firmware v1.0.3.
The convert package needs to be downloaded and drag&droped in the Shelly firmware update area in Web Frontend. Updating via URL does NOT work.
Every step needs to be done exactly as described!

**Comment by TimelessNL** [comment]
I've OTA updated a recently bought Shelly Plus 1PM. And I'm curious as my chip is reported as `ESP32-U4WDH-D rev.3` does the `D` in this case indicate the `D` variant and thus the dual core version? As the [2PM](https://templates.blakadder.com/shelly_plus_2PM.html) had this upgrade in recent versions.

**Comment by TD-er** [comment]
> I've OTA updated a recently bought Shelly Plus 1PM. And I'm curious as my chip is reported as `ESP32-U4WDH-D rev.3` does the `D` in this case indicate the `D` variant and thus the dual core version? As the [2PM](https://templates.blakadder.com/shelly_plus_2PM.html) had this upgrade in recent versions.

See [ESP32 datasheet page 11](https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf)

![image](https://github.com/tasmota/mgos32-to-tasmota32/assets/3751318/b2a95155-6dc2-47d3-a12c-2e9c77b10af3)

**Comment by TimelessNL** [comment]
To my understanding the `ESP32-U4WDH` can either be a single core or dual core.
See [ESPHome Shelly Plus 2PM](https://devices.esphome.io/devices/Shelly-Plus-2PM#hardware-versions):
![afbeelding](https://github.com/tasmota/mgos32-to-tasmota32/assets/10838968/0289e516-6fe1-40c5-8614-a2b8049a0daa)
And (_see highlighted_):
![afbeelding](https://github.com/tasmota/mgos32-to-tasmota32/assets/10838968/d1444834-4890-4f93-93d8-e7dda60b91d4)
Unfortunately I'm unable to open the case, as such I though maybe I can detect the chips version through software.

**Comment by Jason2866** [comment]
Just flash a standard build, if Tasmota does not start anymore it is single core 🤡
Joke aside the detection code of the MCU type is taken from espressif from esptool.py

**Comment by TimelessNL** [comment]
So that basically means the newer Plus 1PM's are dual core?

**Comment by TD-er** [comment]
Not sure how long they may have had stock of the single core chips.
But I think it is rather safe to assume that everything assembled in 2023 would not be using chips produced before 2022.

**Comment by Jason2866** [comment]
@avacon34 @Maximillian Can I close?

**Comment by avacon34** [comment]
Yes, go ahead.

28 Eyl 2023 Per 11:32 tarihinde Jason2866 ***@***.***> şunu
yazdı:
