### ISSUE TITLE
can't drag and drop

### ISSUE THREAD

**Issue by mokkin** [tasmota/mgos32-to-tasmota32#60]
Unfortunately there is no field to drag & drop the new firmware image:

![grafik](https://github.com/tasmota/mgos32-to-tasmota32/assets/2938748/da05dbb9-c734-4cee-8ffb-3ef5b931abd4)

Am I looking at the wrong place?

**Comment by Jason2866** [comment]
Do as in the workflow told. Update Shelly firmware to latest.

**Comment by mokkin** [comment]
Please reopen.
As you can see in the screenshot, I already had the latest firmware installed. I updated even to the latest BETA, but I still can't find any field for drag and drop:

![grafik](https://github.com/tasmota/mgos32-to-tasmota32/assets/2938748/2884f661-e162-4af2-9182-78beb7dc0228)

**Comment by Jason2866** [comment]
Which device is it? It is not visible in the screenshot nor you mentioned it.
All Shelly esp32 driven devices supported by this tool do show the intern Shelly name on the main page.

**Comment by mokkin** [comment]
It's a Shelly Plug S.

**Comment by mokkin** [comment]
sorry, I have no plus...

**Comment by Jason2866** [comment]
Look here https://github.com/arendst/mgos-to-tasmota
