### ISSUE TITLE
Stuck with the Partition Wizard step

### ISSUE THREAD

**Issue by Dilergore** [tasmota/mgos32-to-tasmota32#63]
Hi,

I have successfully upgraded multiple Shelly Plus 2PMs following the same steps. That said, I have this single device where I am having issues, it seems I am stuck and cannot proceed after the partition wizard:
<img width="564" alt="image" src="https://github.com/tasmota/mgos32-to-tasmota32/assets/14315890/0659854c-86d3-469b-ba9a-1774a2a746b1">

I tried to re-apply 12.5.0 as described [here](https://github.com/arendst/Tasmota/discussions/19162) without luck.

Any idea how I could resolve this?

**Comment by Jason2866** [comment]
Since the tool can't find the app sizes, probably only a serial flash can recover the device.
Looks like the partition info has been corrupted.

**Comment by Dilergore** [comment]
Thanks @Jason2866!

So after FS increase, the Partition Manager disappeared. When I checked the auto-config it was showing like i never applied it, so I reapplied it. Once I reapplied the auto-config, the partition manager was there again, and it was not showing the ERROR for Step 1, so I was able to run it with success and everything is working and I am on the latest version.
