### ISSUE TITLE
request support for shelly plug plus S V2

### ISSUE THREAD

**Issue by Roksvaag** [tasmota/mgos32-to-tasmota32#65]
Hi there,
is it possible to add support for this device? Unless i'm mistaken it's not supported yet
link to Shelly KB: https://kb.shelly.cloud/knowledge-base/shelly-plus-plug-s-v2 
Screenshot of device info
![image](https://github.com/tasmota/mgos32-to-tasmota32/assets/113937978/39c68edc-b787-453a-907d-f4ef720ca50f)

**Comment by Jason2866** [comment]
What happens with this one https://github.com/tasmota/mgos32-to-tasmota32/releases/download/v13.4.2/mgos32-to-tasmota32-PlusPlugS.zip ?

**Comment by Roksvaag** [comment]
As there's no option to "drag 'n drop" the zip into the UI, I've tried just using the link. It loads for about 15 sec, then I get an error message saying "Your Shelly has failed to update". please refer to attached image. 

![bilde](https://github.com/tasmota/mgos32-to-tasmota32/assets/113937978/09685dcb-8976-4744-ac90-a2268e58b0f9)

**Comment by Jason2866** [comment]
The Shelly firmware is not the actual one. Download from here https://updates.shelly.cloud/update/PlusPlugS and provide this original Shelly update package.

**Comment by Th0maz** [comment]
I had the same problem and solved it by hosting the update package locally using https://github.com/TheWaWaR/simple-http-server and put the link from my local network into the custom firmware field.

After I read something about "[Devices with firmaware v1.10+ cannot be flashed OTA anymore](https://templates.blakadder.com/shelly_plus_2PM.html)" I thought it would not be a good idea to let the Shelly device update itself to the latest firmware version.

**Comment by Roksvaag** [comment]
Thank you guys, I'll look into it. 
 @Th0maz , did you use the update package linked by Jason? Are you also using the V2-edition of the plug plus s?

**Comment by Th0maz** [comment]
I used different devices (I think Shelly Plus 2PM or Shelly Plus PM Mini). And since there was no drag-and-drop area, I used the local web server to "inject" the matching firmware update package.

**Comment by Jason2866** [comment]
Closing since no feedback. Flashing the Shelly Plus Plug S is supported.
