### ISSUE TITLE
New device: Shelly Plus RGBW PM

### ISSUE THREAD

**Issue by nerdosity** [tasmota/mgos32-to-tasmota32#66]
![image](https://github.com/user-attachments/assets/0e4b49c0-8229-4d00-ab5c-55bfe27a7d81)

https://kb.shelly.cloud/knowledge-base/shelly-plus-rgbw-pm

Still hadn't be able to caught the button and the onboard LED pin. 
Can you build a firmware for this? I would gladly test it. Maybe if you enable configuration on safe GPIOs I can test which one is which.

Edit: advice me how to search for the PM device please

**Comment by nerdosity** [comment]
![image](https://github.com/user-attachments/assets/9dba6081-b473-4228-b48e-e45e3241f2ce)

![image](https://github.com/user-attachments/assets/9101c2e9-eda9-4c3d-b61f-bf5caf02f483)

![image](https://github.com/user-attachments/assets/6f0350d9-6dba-4218-bcbf-5b9d11049bda)

![image](https://github.com/user-attachments/assets/ba78cfda-b69b-4010-a527-74e8a6251047)

![image](https://github.com/user-attachments/assets/71abe019-c1f4-4a88-aadf-e7c9f17ad652)

**Comment by Jason2866** [comment]
OTA Support should be easily to add. But first full Tasmota support should be done.
@arendst  Are you planning to buy one? Looks like a small job for you to add ;-)

**Comment by TD-er** [comment]
No visible exposed pads at the bottom of the PCB?
All vias look to be covered in soldermask and probing directly onto the ESP32 pins is rather tricky.

**Comment by arendst** [comment]
I'll order one and see if I can use PCBite to connect to it.

**Comment by nerdosity** [comment]
Yes, will post a lower photo of the downside.
The usual header for shelly products is there.

**Comment by arendst** [comment]
Still waiting for my order to arrive.

> advice me how to search for the PM device please

From the pictures I see there is no specific PM device. They probably use some analog inputs to measure voltage and (total) current considering R001 at input.

**Comment by arendst** [comment]
Almost there

![image](https://github.com/user-attachments/assets/88b5dfce-24a8-4493-889a-e84ad075ddbf)

**Comment by nerdosity** [comment]
> Almost there
> 
> ![image](https://private-user-images.githubusercontent.com/11044339/354134580-88b5dfce-24a8-4493-889a-e84ad075ddbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDU5MzksIm5iZiI6MTcyMjUwNTYzOSwicGF0aCI6Ii8xMTA0NDMzOS8zNTQxMzQ1ODAtODhiNWRmY2UtMjRhOC00NDkzLTg4OWEtZTg0YWQwNzVkZGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA5NDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMGZiNDRlOTgzM2ZlZjhmYTZmZmQzNDg3NTBiYTJlMDk1ODY2ZjBhZGM1ODYwODVkYTBkMjJmOTEzYWRkZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vkKLXvG4G-73p7thpSpz3gApOBQfW81lz1KWZueR_0U)

Was my pinout good?

**Comment by arendst** [comment]
Most. GPIO24 does not exist. It needs to be GPIO04 for the white channel

**Comment by nerdosity** [comment]
Did you checked if the inputs are galvanically insulated or not?

**Comment by TD-er** [comment]
Purely based on the pictures, I really doubt there will be any isolation.

**Comment by arendst** [comment]
Indeed, as can be seen on the pictures the inputs are connected to the ADC GPIOs using a resistor bridge. This bridge allows for connecting either a button or a 10k potentiometer. I have both working but currently ADC user configuration is very difficult using commands ``AdcParam`` for each GPIO as you need at least 7 of them for temperature, voltage, current and potentiometers/buttons. I'm adding a new command making more sense to operate.

**Comment by arendst** [comment]
Using latest dev branch you could play with Tasmota on Shelly Plus RGBW PM. See below info:
```
 * Template {"NAME":"Shelly Plus RGBW PM Pot.meter","GPIO":[1,0,0,0,419,0,0,0,0,0,544,0,0,0,0,1,0,0,1,0,0,416,417,418,0,0,0,0,0,4736,11264,11296,4704,0,4705,0],"FLAG":0,"BASE":1}
 * AdcParam1 1,32000,40000,3350      <- Temperature parameters
 * AdcParam2 1,1161,3472,10,30       <- Voltage parameters
 * AdcParam3 1,960,1017,0.01,0.706   <- Current parameters
 * AdcParam4 1,1552,176,3,1          <- I1 Potentiometer RGBW or RGB if SO37 128
 * AdcParam4 1,1552,176,3,3          <- I1 Potentiometer RGBW or RGB if SO37 128 without fading
 * AdcParam5 1,1552,176,3,1          <- I3 Potentiometer W if SO37 128
 * Fade 1
 * Speed 6
 * VoltRes 2
 * WattRes 2
 * 
 * Template {"NAME":"Shelly Plus RGBW PM Button","GPIO":[1,0,0,0,419,0,0,0,0,0,544,0,0,0,0,1,0,0,1,0,0,416,417,418,0,0,0,0,0,4736,11264,11296,4800,4801,4802,4803],"FLAG":0,"BASE":1}
 * AdcParam1 1,32000,40000,3350      <- Temperature parameters
 * AdcParam2 1,1161,3472,10,30       <- Voltage parameters
 * AdcParam3 1,960,1017,0.01,0.706   <- Current parameters
 * AdcParam4 1,511                   <- I1 Button
 * AdcParam5 1,511                   <- I2 Button
 * AdcParam6 1,511                   <- I3 Button
 * AdcParam7 1,511                   <- I4 Button
 * Fade 1
 * Speed 6
 * VoltRes 2
 * WattRes 2
```
![image](https://github.com/user-attachments/assets/0c003126-82fd-4053-8cf0-b7778b55239a)

**Comment by nerdosity** [comment]
Do you think we could use something like this? 
![Screenshot_2024-08-04-23-04-59-81_b5f6883d2c20a96c53babc0b4ac88108](https://github.com/user-attachments/assets/f5d2f15c-d819-4f24-8cfc-422e1ae7eb0b)
Even RX TX and GPIO0 are not galvanically safe, right?

I sourced an Adafruit Qwiic RGB encoder and now I can't use it 😔

**Comment by arendst** [comment]
That's a rotary encoder but NOT a 10k potentiometer. Not sure if that would work considering the fact that the device only supports analog inputs and I have never tested the rotary encoder that way.

**Comment by nerdosity** [comment]
Do you think it's possible to use the I2C device above on other pins? Or are they all insulated and not 5v safe?

**Comment by arendst** [comment]
The I2C device is currently not supported by Tasmota.

The rotary encoder on the other hand is supported. I've connected my rotary encoder to the Shelly Plus RGBW and it works "out-of-the-box" (to my suprise). Apparently the analog inputs also work fine if configured as normal Buton, Switch or Rotary Encoder.

```
17:28:25.989 BTN: Button1 multi-press 1
17:28:26.492 SRC: Button
17:28:26.504 MQT: stat/plusrgbwpm/RESULT = {"POWER":"OFF"}
17:28:26.509 MQT: stat/plusrgbwpm/POWER = OFF
17:28:28.209 CFG: Saved, Count 211, Bytes 4096
17:28:29.660 SRC: Light
17:28:29.755 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":60,"Color":"99999900","HSBColor":"0,0,60","White":0,"Channel":[60,60,60,0]}
17:28:30.047 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":70,"Color":"B3B3B300","HSBColor":"0,0,70","White":0,"Channel":[70,70,70,0]}
17:28:30.996 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":80,"Color":"CCCCCC00","HSBColor":"0,0,80","White":0,"Channel":[80,80,80,0]}
17:28:32.150 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":90,"Color":"E6E6E600","HSBColor":"0,0,90","White":0,"Channel":[90,90,90,0]}
17:28:32.396 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFFFFF00","HSBColor":"0,0,100","White":0,"Channel":[100,100,100,0]}
17:28:32.651 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFFFFF00","HSBColor":"0,0,100","White":0,"Channel":[100,100,100,0]}
17:28:32.847 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFFFFF00","HSBColor":"0,0,100","White":0,"Channel":[100,100,100,0]}
17:28:33.048 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFFFFF00","HSBColor":"0,0,100","White":0,"Channel":[100,100,100,0]}
17:28:33.154 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFFFFF00","HSBColor":"0,0,100","White":0,"Channel":[100,100,100,0]}
17:28:33.367 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFFFFF00","HSBColor":"0,0,100","White":0,"Channel":[100,100,100,0]}
17:28:34.449 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":90,"Color":"E6E6E600","HSBColor":"0,0,90","White":0,"Channel":[90,90,90,0]}
17:28:35.547 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":80,"Color":"CCCCCC00","HSBColor":"0,0,80","White":0,"Channel":[80,80,80,0]}
17:28:36.050 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":70,"Color":"B3B3B300","HSBColor":"0,0,70","White":0,"Channel":[70,70,70,0]}
17:28:36.657 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":60,"Color":"99999900","HSBColor":"0,0,60","White":0,"Channel":[60,60,60,0]}
17:28:37.291 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":50,"Color":"80808000","HSBColor":"0,0,50","White":0,"Channel":[50,50,50,0]}
17:28:37.844 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":40,"Color":"66666600","HSBColor":"0,0,40","White":0,"Channel":[40,40,40,0]}
17:28:38.497 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":30,"Color":"4D4D4D00","HSBColor":"0,0,30","White":0,"Channel":[30,30,30,0]}
17:28:39.152 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":20,"Color":"33333300","HSBColor":"0,0,20","White":0,"Channel":[20,20,20,0]}
17:28:39.812 MQT: stat/plusrgbwpm/RESULT = {"POWER":"ON","Dimmer":10,"Color":"1A1A1A00","HSBColor":"0,0,10","White":0,"Channel":[10,10,10,0]}
17:28:41.197 SRC: Light
17:28:41.307 MQT: stat/plusrgbwpm/RESULT = {"POWER":"OFF","Dimmer":0,"Color":"00000000","HSBColor":"0,0,0","White":0,"Channel":[0,0,0,0]}
17:28:43.123 MQT: stat/plusrgbwpm/RESULT = {"POWER":"OFF","Dimmer":0,"Color":"00000000","HSBColor":"0,0,0","White":0,"Channel":[0,0,0,0]}
17:28:44.229 CFG: Saved, Count 212, Bytes 4096
```

Using this template
```
{"NAME":"Shelly Plus RGBW PM User","GPIO":[1,0,0,0,419,0,0,0,0,0,544,0,0,0,0,1,0,0,1,0,0,416,417,418,0,0,0,0,0,4736,11264,11296,1,1,1,1],"FLAG":0,"BASE":1}
```
and this module config:
![image](https://github.com/user-attachments/assets/a4758990-0806-40af-b557-2d9ac1d7e4cd)

**Comment by Angmar3019** [comment]
First of all, thank you for the great work here. I saw you already had success with the device and referenced the dev branch to test it. Since a new version has been released in the meantime, can I just flash it to test and then use one of your templates?

Do you know how long it will take until the device is fully supported like the other devices and a zip is available for download? Is there anything I can do to help with testing in the meantime?

**Comment by arendst** [comment]
Yes. v14.2.0 supports the Shelly Plus RGBW PM.

@Jason2866 how to go forward adding this to our mgos to tasmota site (if at all possible considering the latest FW changes of shelly denying our update procedure).

**Comment by Jason2866** [comment]
@Angmar3019 For adding support i need the Shelly intern device name. This is visible on the main Shelly Web page from the device. With this i can look at the Shelly update server to fetch a Shelly update zip for the device. In the Shelly update package all Infos and "parts" are there to build the convert zip.

**Comment by RavenSystem** [comment]
PlusRGBWPM

**Comment by Angmar3019** [comment]
My Shelly was still delivered with an old firmware under v1.4.x, so I could still test the upgrade process via OTA if needed.

![image](https://github.com/user-attachments/assets/90cc2286-8190-4591-a299-8a57fb2da28b)

**Comment by Angmar3019** [comment]
Many thanks for the advice and the new package. I will test it directly and give you feedback if it works.

**Comment by Jason2866** [comment]
Mandantory is the Autoconfiguration step!!! Else you end in a bricked device! The device is already listed in the menu.

**Comment by Angmar3019** [comment]
Great that is now the second device that has been successfully converted to tasmota with your help. Everything, including the memory expansion, worked perfectly. I have also tested all inputs and outputs with an LED strip and buttons and they all work.

Unfortunately the template that was included in your package and the one that @arendst has provided shows the wrong temperature for me.

![image](https://github.com/user-attachments/assets/291d4ae9-fb51-4c56-8775-3b9eeca4c3d0)

The screenshot shows the button template since the wattage and voltage are also read incorrectly in my case.

**Comment by arendst** [comment]
In addition to the template you'll need a lot of other commands.

See below:
```
 * Template {"NAME":"Shelly Plus RGBW PM Pot.meter","GPIO":[1,0,0,0,419,0,0,0,0,0,544,0,0,0,0,1,0,0,1,0,0,416,417,418,0,0,0,0,0,4736,11264,11296,4704,0,4705,0],"FLAG":0,"BASE":1}
 * AdcGpio33 32000,40000,3350        <- Temperature parameters
 * AdcGpio34 1161,3472,10,30         <- Voltage parameters
 * AdcGpio35 960,1017,0.01,0.706     <- Current parameters
 * AdcGpio36 1552,176,3,1            <- I1 Potentiometer RGBW or RGB if SO37 128
 * AdcGpio36 1552,176,3,3            <- I1 Potentiometer RGBW or RGB if SO37 128 without fading
 * AdcGpio38 1552,176,3,1            <- I3 Potentiometer W if SO37 128
 * Fade 1
 * Speed 6
 * VoltRes 2
 * WattRes 2
 * 
 * Template {"NAME":"Shelly Plus RGBW PM Button","GPIO":[1,0,0,0,419,0,0,0,0,0,544,0,0,0,0,1,0,0,1,0,0,416,417,418,0,0,0,0,0,4736,11264,11296,4800,4801,4802,4803],"FLAG":0,"BASE":1}
 * AdcGpio33 32000,40000,3350        <- Temperature parameters
 * AdcGpio34 1161,3472,10,30         <- Voltage parameters
 * AdcGpio35 960,1017,0.01,0.706     <- Current parameters
 * AdcGpio36 511                     <- I1 ADC Button
 * AdcGpio37 511                     <- I2 ADC Button
 * AdcGpio38 511                     <- I3 ADC Button
 * AdcGpio39 511                     <- I4 ADC Button
 * Fade 1
 * Speed 6
 * VoltRes 2
 * WattRes 2
```

**Comment by Angmar3019** [comment]
Oh thanks for the explanation, I didn't know that yet. Now the values are correct.

**Comment by Jason2866** [comment]
added this settings to the Autoconfig template
```
 * AdcGpio33 32000,40000,3350        <- Temperature parameters
 * AdcGpio34 1161,3472,10,30         <- Voltage parameters
 * AdcGpio35 960,1017,0.01,0.706     <- Current parameters
 * Fade 1
 * Speed 6
 * VoltRes 2
 * WattRes 2
 ```

**Comment by Jason2866** [comment]
Version is online in release section supporting Shelly fw >= v.14.x
