### ISSUE TITLE
Shelly Plus 1 PM not responding after upgrade to german firmware

### ISSUE THREAD

**Issue by polojoe** [tasmota/mgos32-to-tasmota32#73]
I successfully converted my shelly plus 1 pm to tasmota, then I finally wanted to flash the german firmware from http://ota.tasmota.com/tasmota32/release/tasmota32-DE.bin
Now the shelly isn't responding any more.

**Comment by Jason2866** [comment]
Not an issue of the the convert process.
Wrong firmware used. The shelly plus 1 pm has an esp32-solo1 inside. When a dual core firmware is used it will stuck in bootloader. Only way to recover is serial flash.
