### ISSUE TITLE
Shelly PM4 Pro Web Not Found! is bricked? need Help!

### ISSUE THREAD

**Issue by bigbutler** [tasmota/mgos32-to-tasmota32#76]
I did it as described.
After restarting I can no longer access the web interface, it just says Not Found?
WiFi connection can still be seen from the Shelly pm4 Pro. what can I do now?

**Comment by bigbutler** [comment]
I mean all Brick SHelly´s all my Shellys are gone all dead wtf!

**Comment by zeus86** [comment]
most likely the same as my problem. see #75 .

**Comment by Jason2866** [comment]
Issue was caused from new Shelly fw 1.4.x. The latest convert packages are compatible with Shelly fw 1.4.x
