### ISSUE TITLE
Shelly Mini Gen3 - No AP appears after loading mgos32-to-tasmota32-Mini1G3.zip

### ISSUE THREAD

**Issue by alexstarke** [tasmota/mgos32-to-tasmota32#77]
I am pretty sure that I followed the [instructions](https://github.com/tasmota/mgos32-to-tasmota32?tab=readme-ov-file#lets-start) thoroughly to convert the Shelly Mini Gen3 modules. Still I am stuck after loading mgos32-to-tasmota32-Mini1G3.zip, no tasmota AP appears. 
Anything I can do to recover the module? Is it possible to serial flash the Shelly Mini Gen3? 

Any help is much appreciated, Thanks!

**Comment by rp2019433** [comment]
Hi.
Please take a look at #68 and #74 .

**Comment by Jason2866** [comment]
Please try https://github.com/tasmota/mgos32-to-tasmota32/releases/tag/v14.1.0

**Comment by alexstarke** [comment]
> Please try https://github.com/tasmota/mgos32-to-tasmota32/releases/tag/v14.1.0

Thanks a lot for looking into this! I need to order new modules, so feedback will take a while ...

**Comment by StomaNL** [comment]
Flashed my PM Mini Gen3, Tasmota AP is up, filled in my network credentials but never connects to my network. AP shows up again but now I can't connect to the device, keeps throwing me off when it evens connect at all (on laptop and phone). 

Is flashing Tasmota over serial the way to resurrect?

**Comment by Jason2866** [comment]
Probably the solution is #80

**Comment by alexstarke** [comment]
> > Please try https://github.com/tasmota/mgos32-to-tasmota32/releases/tag/v14.1.0
> 
> Thanks a lot for looking into this! I need to order new modules, so feedback will take a while ...

I finally got to testing it successfully with a new device, thanks for you support!
