### ISSUE TITLE
Cannot update Shelly Mini1G3 12.5 to 14.0

### ISSUE THREAD

**Issue by jankkm** [tasmota/mgos32-to-tasmota32#79]
I converted the Shelly Mini 1 G3 a while ago and it worked good for a while and today I did an OTA update which I now know was a mistake.

I can still use it but it is stuck on Tasmota 12.5 and I can do an update to 14.0 from the release page but after the reboot it is still on 12.5

I need Matter support so this is quite a problem for me.

Is there a way to fix this without serial access?
![IMG_9138](https://github.com/user-attachments/assets/c0323cbe-9658-47b3-8e62-e32279ad405a)
![IMG_9137](https://github.com/user-attachments/assets/cec93eb8-b43e-4c19-b7c2-e8a8f16318ec)

**Comment by Jason2866** [comment]
If the Autoconfig step was not done right after the OTA convert process, the locked Shelly bootloader is not replaced and device can't not be updated via OTA.
Anyways you can try the Autoconfig step again. This step will update to latest Tasmota version if it is possible (no locked Shelly bootloader). If this does not work serial flash is the only way to update to a newer Tasmota version

**Comment by jankkm** [comment]
I‘m not sure if you unterstood me correctly. Is did the full conversion correctly a while ago and it worked fine (with Matter). Today I clicked on the OTA Firmware Button
![IMG_9139](https://github.com/user-attachments/assets/42dce348-9084-4200-ac30-20cca5f85a97)
Does the bootloader have to be replaced again?

**Comment by Jason2866** [comment]
If the Autoconfig step was not done the locked bootloader is not replaced. With the Shelly bootloader there is no update of the Tasmota firmware possible. So the step was recommended from me to be sure to have a unlocked bootloader. There is no reason when all this is done that a OTA update does not work.
Are you sure the device can reach the OTA Server? The device needs Internet access.
You can alternatively download the newer firmware and provide via file firmware upgrade.

**Comment by jankkm** [comment]
Thanks for your response.

The autoconfig step was done so I guess I have a different problem.

I downloaded the newest release here (https://github.com/tasmota/mgos32-to-tasmota32/releases/download/v14.1.0/mgos32-to-tasmota32-Mini1G3.zip), unpacked it and used the "tasmota32c3.bin" for the firmware upgrade. This seems to work fine but afterwards I am still on Tasmota 12.5

My suspicion is that the upload does not work for some reason so it uses a firmware bin that is still on the device. But I don't know how to check for that.

**Comment by Jason2866** [comment]
As expected, the convert package does have v12.5 Tasmota firmware.
Download actual firmware from https://ota.tasmota.com/tasmota32/

**Comment by jankkm** [comment]
Silly me, of course it works. Thank you so much for your patience!
