### ISSUE TITLE
Shelly PlusPMMini: no Partiton Wizard, no Power

### ISSUE THREAD

**Issue by daUser** [tasmota/mgos32-to-tasmota32#8]
Hi,

im stuck on Step 10:
There is no Partition Wizard.

Also my PlusPMMini doesn't show me any Power. And the Temperature isn't correct.

Are there any solutions?

![Tasmota_PlusPMMini](https://github.com/tasmota/mgos32-to-tasmota32/assets/5454552/13d77f5c-15e8-48a1-87ef-e057a79b33f6)

**Comment by Jason2866** [comment]
@daUser this is needed `so21 1`

**Comment by daUser** [comment]
Hi,
some Time is gone,.. it's difficult to find the time at the Moment...

I have found the Partition-Wizard - it was behind the Button "Consoles", my fault.

So i have done Step 10 and 11. And then i had this GUI:
![Tasmota_PlusPMMini](https://github.com/tasmota/mgos32-to-tasmota32/assets/5454552/6b1ae643-c5ab-4415-a3fd-a5a79cf81457)
I have done an upgrade to 13.1.0.4 "tasmota32**s3**.bin" from https://ota.tasmota.com/tasmota32/.
After this a second Time `so21 1`.
Now i get the Power Informations, a little bit calibration and this is good.

But: the Analog1 Temperature shows 46,1°C, in reality i have 21,5°C. An at this difference i can't work with 'TemperatureOffset'.
