### ISSUE TITLE
[Mini1G3] Shelly firmware >= 1.4.x only 1.3.3 available

### ISSUE THREAD

**Issue by MPW1412** [tasmota/mgos32-to-tasmota32#80]
Hello,

readme says to update Shelly original firmware to 1.4.x. However, only 1.3.3 is available.

![image](https://github.com/user-attachments/assets/3a3f051c-0fd5-49e6-b709-54b04462786c)

I clicked on the circling arrows, nothing beyond 1.3.3. Is 1.3.3 supported for migration?

Device is marked tested. So I'm a bit confused.

Best,
Matthias

**Comment by Jason2866** [comment]
Oh what a mess from Shelly. Indeed there is no update package available for the Mini1G3
to fw 1.4x. The Mini1G3 was tested before the fw 1.4x
So for the Mini1G3 this version should work. https://github.com/tasmota/mgos32-to-tasmota32/releases/download/v13.4.1/mgos32-to-tasmota32-Mini1G3.zip

**Comment by Jason2866** [comment]
Readme updated. Thx for providing this information.
