### ISSUE TITLE
Tasmota SSID - No web page

### ISSUE THREAD

**Issue by yaba** [tasmota/mgos32-to-tasmota32#81]
After following the tutorial, I can see the new Tasmota SSID, connect to it and ping 192.168.4.1 as expected.

However, no webpage is displayed and device enters a reboot loop saying the partition table has an error.

Shelly PM Mini Gen 3 previously running 1.4.x firmware.

EDIT: Fixed by flashing it using Tasmota web tool. It's a pain to flash 10 devices manually; let me know when this is fixed.

Thanks.

**Comment by mr-awk** [comment]
I did also follow the instructions with firmware 1.4.4, and now I only see the Shelly SSID, and can't connect to that network. So I would say that PMMiniG3 with firmware 1.4.4 is not compatible with the installation instructions for now.

**Comment by Jason2866** [comment]
@mr-awk if the Shelly AP comes up the mandantory steps 8-10 are not done.
