### ISSUE TITLE
Tasmota Template fopr Shelly 1G3M

### ISSUE THREAD

**Issue by SirFr0zzy** [tasmota/mgos32-to-tasmota32#87]
Hello there,

i recently flashed my Shelly 1 Mini Gen 3 with Tasmota over this tool. I got the device into my Local WiFi Network, but i don't know how to configure it properly to toggle the Relay. Any help is appreciated.

Elias
<img width="434" alt="Bildschirmfoto 2024-11-01 um 14 34 28" src="https://github.com/user-attachments/assets/2663cf95-29b9-4dc3-b758-e5f663faa677">

**Comment by Jason2866** [comment]
When the Autoconfig step is done the device restarts and every needed setup is done.
No manually setup is needed.
