### ISSUE TITLE
Shelly Plus i4 successfully flashed to Tasmota opens Shelly AP after restart

### ISSUE THREAD

**Issue by waldorffsmama** [tasmota/mgos32-to-tasmota32#91]
I have bought a couple of Shelly Plus I4. Now after updating the Shelly to firmware 1.4.4, I managed to successfully flash Tasmota firmware with the mgos32-to-tasmota32-PlusI4a.zip file. It restarts, I find the Tasmota AP as usual, set it up and change all parameters in the console as needed.

After restarting, it does not login to my WiFi-Network but opens again a Shelly HotSpot. There is no WebUI anymore on 192.168.33.1 and I am stuck. This is the second device where it happens.

Any ideas what could have gone wrong?

**Comment by Jason2866** [comment]
I would need the device to do investigations. Without it is hard / impossible to find the reason for failing.

**Comment by waldorffsmama** [comment]
I can send one to you.

**Comment by Jason2866** [comment]
You can contact me on Tasmota Discord Server https://discord.gg/Ks2Kzd4
via PM for details. My nick is Jason2866 there too.

**Comment by gerritb** [comment]
Shelly 1 Mini Gen3 has the exact same behavior if that helps debugging

**Comment by Tillomar** [comment]
Shelly Plus Plug S (on 20241011-114442/1.4.4-g6g2a586) also has this behavior. Bricked one, recovery procedure ([https://github.com/tasmota/mgos32-to-tasmota32/issues/75#issuecomment-2379974905]) does not work; waiting for your analysis.

**Comment by copperfield74** [comment]
Same problem here with Shelly Plus Plug S. Was able to recover but same problem after second try.

**Comment by copperfield74** [comment]
Same problem here with Shelly Plus Plug S. Was able to recover but same problem after second try.

**Comment by Jason2866** [comment]
@waldorffsmama thx for sending a Shelly i4. Can investigate now.

**Comment by Tillomar** [comment]
Jason, if having a Shelly Plus Plug S too would help, let me know.

**Comment by Jason2866** [comment]
@Tillomar Dont know if I find something with the Shelly Plus Plug S. If you don't mind sending me one (don't send anything back). Ping me on Discord. For sure I will investigate!!
The Shelly Plus I4 investigation did not show any problems. So maybe I find no problem with the Shelly Plug S too. There is the chance that a WiFi network problem during the convert process occurs. If this happens device is soft bricked.

**Comment by waldorffsmama** [comment]
> @waldorffsmama Rebuilded the Shelly i4 firmware (from the leftovers on the device and the orig. Shelly update firmware zip) and flashed on the device. The I4 booted up successfully with Shelly firmware. Dragged & Dropped the Shelly I4 convert zip. Device converted successfully to Tasmota. After Autoconfig converted to safeboot scheme without any problems. Honestly idk what went wrong in your attempts. Maybe wrong conver zip used? The device you sent me is an I4 with an esp32 solo1 (No 3rd gen device).
Amazing. And how did I manage to do the same error twice? Will start with another Shelly I4 from scratch and let you what I am doing step-by-step.

**Comment by waldorffsmama** [comment]
@Jason2866  
Here is how I am flashing to Tasmota. Would you mind checking if there is anything wrong or unusual?

1) Connect Shelly i4 to 12V
2) Access AP and enter Wifi information, turn on Wifi
3) Access user interface from new IP address, navigate to Firmware / Upgrade and update to 1.3.3...
4) It reboots
5) Update to 1.4.4 (stable)
6) Now I would download http://ota.tasmota.com/tasmota32/release/tasmota32solo1.bin and drag and drop the file into the "firmware file image" box

I am stopping at this point and would like to ask you to confirm that I have followed the correct procedure. All correct?

**Comment by Tillomar** [comment]
Comment from my side:
I DID follow the steps -- however, after step 8 (autokonfiguration) my device DID NOT come up again.

**Comment by Jason2866** [comment]
@Tillomar You can send me a (bricked) Shelly Plus Plug S for free if you want. I will not send back the device! 
Will try to find the reason for the Shelly Plus Plug S fail attempt in your case.
