### ISSUE TITLE
Plus2PM - taśmowa minimal:(

### ISSUE THREAD

**Issue by wirszews** [tasmota/mgos32-to-tasmota32#93]
Hi,
I have shelly plus 2pm
I uploaded mgos32 to tasmota 32, but then I don't know what tempted me to install tasmota minimal (9.2.0).

Then I tried to upload mgos again but it does not accept it is Upload failed. Can I somehow upload without disassembling the socket?

I currently have a screen with Tasmota Minimal

**Comment by Jason2866** [comment]
There is no Tasmota minimal for esp32. If you have the safeboot version flashed you can try to flash tasmota32solo1
