### ISSUE TITLE
Inverted Dimmer Behavior on Shelly 0-10V with Tasmota

### ISSUE THREAD

**Issue by Rob-Myr** [tasmota/mgos32-to-tasmota32#96]
Hi,

I’m experiencing an issue with my Shelly 0-10V device running Tasmota. While the device is functional, the dimming behavior appears to be inverted:

- When I dim to 0%, the 0-10V output reads 10V.
- When I dim to 100%, the output reads 0V.

This inverted behavior also affects the toggle functionality:

- When I toggle off the lights, they turn on at full power (10V output).
- When I toggle on, the lights turn off (0V output).

This behavior is opposite to what I would expect.

I have searched the documentation and configuration options but haven’t been able to find a way to invert the dimmer behavior. Am I missing a specific setting or configuration? Is there a way to invert the dimmer output in Tasmota, or is this behavior expected for this device?

Thank you for your support and for maintaining such an excellent project! Please let me know if additional details are needed.

**Comment by Jason2866** [comment]
Please open an issue in main project Tasmota github. https://github.com/arendst/Tasmota/issues This issue is only for problem with the OTA convert tool. Thx.
